export type Entitlement = 
    'create-custom-tba-responses'
  | 'edit-potato-level'
  | 'manage-pit-scouting'
  | 'manage-roles'
  | 'manage-tba'
  | 'manage-universe'
  | 'upload-pictures'
  | 'view-checklist'
  | 'view-pit-scouting'
  | 'view-potatoes'
  | 'view-roles'
  | 'view-scouting'
  | 'view-strategy'
  | 'view-tba-info'
  | 'view-universe';
export type Group = 
    'TBA'
  | 'Potatoes'
  | 'Scouting'
  | 'Roles'
  | 'Universe'
  | 'FIRST'
  | 'Checklists'
  | 'Strategy';
